<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Omrina.Platform</AssemblyName>
    <RootNamespace>Omrina.Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Omrina.Core\Omrina.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>
</Project>
