<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Omrina.Scanning</AssemblyName>
    <RootNamespace>Omrina.Scanning</RootNamespace>
  </PropertyGroup>
</Project>
